### PR TITLE
Feature/on prem

### PR DESCRIPTION
**Pull request by Kraviecc**
Hi guys!

I've tried to run some tests on CRM onprem with this library. After digging some time in your code I've changed a lot and it works now.

I've created shared projects to handle onprem as well as online versions of crm. I've also added localized resource for common strings used in tests.

Tested on:
OnPremise (8.2.0.749) (DB 8.2.0.749) (Polish language)
Online Version 1612 (9.0.0.3292) (DB 9.0.0.3292) (English language).

Take a look at this. It's up too you whether it's worth merging. Anyway if you see that something should be changed I will be pleased for feedback.

### CODE REVIEW

**Comment by john-h-zheng** [comment]
This looks interesting. However, how do I get a local copy to play with?

**Comment by Kraviecc** [comment]
Hi @john-h-zheng,

you can clone or download sources from my fork (https://github.com/Kraviecc/EasyRepro) and start testing. Build solution and use Microsoft.Dynamics365.UIAutomation.Api.OnPrem or Microsoft.Dynamics365.UIAutomation.Api.Online assembly as needed along with Microsoft.Dynamics365.UIAutomation.Reference and Microsoft.Dynamics365.UIAutomation.Browser because they are referenced. 

If you'll find any bugs or you'll have any ideas of new features just let me know!

PS. I've recently added support for Microsoft Dynamics® CRM 2016 8.1 (8.1.0.x) (DB 8.1.0.x) onpremise version.

**Comment by kenglover** [comment]
Having this work for on-prem would be really useful.  I encourage the repository keepers to accept the merge request or develop their own supports for on-prem.

**Comment by dtu11** [comment]
Ok, I apologize for the delay in handling this feature.   We pushed a lot of changes since the PR was submitted that caused quite a few conflicts.   We renamed files and removed prefixes that would have required a manual merge so instead we created a separate branch that includes the changes.   It won't be managed moving forward but we're looking at the changes to see if we can incorporate them into a future release.  This will enable us to have one branch that works with both Online as well as OnPremise. 

If someone wants to take the time to try and merge the updates in 9.0 with the OnPremise branch, we can approve the PR to do so.    Unfortunately our team won't have the time to try and do this over the next few months.  

Thanks

Daren

**Pull request closed without merging**
