### PR TITLE
Update webclient for mfa validation

### PR DESCRIPTION
**Pull request by imartinflores**
Validate null value on MFA before executing the do-while.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (updates to documentation, formatting, etc.)

### All submissions:

- [x] My code follows the code style of this project.
- [x] Do existing samples that are effected by this change still run?
- [ ] I have added samples for new functionality. 
- [x] I raise detailed error messages when possible.
- [x] My code does not rely on labels that have the option to be hidden.

### Which browsers was this tested on?

- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge

### CODE REVIEW

**Review by TYLEROL — APPROVED** [review]

**Comment by tpalus** [comment]
I'm trying to run tests without mfa(xrmApp.OnlineLogin.Login(_xrmUri, _username, _password)). After those changes, automated software will not click button "yes" on stay signed dialog because mfa is null.

**Comment by tpalus** [comment]
@TYLEROL I think it's useless to add condition based on mfa, because it is already include in _EnterOneTimeCode_. 

Here is screenshot:
image

I run test without current changes and it works. It would be better to keep code as before in my opinion. What do you think?

**Comment by imartinflores** [comment]
@tpalus for me, was the other way around, even the validation is on EnterOneTimeCode, it was throwing this exception:

throw new InvalidOperationException("Something went wrong entering the OTC. Please check the MFA-SecretKey in configuration.");

I tried the login without mfa and was not failing. Will give it another try and double check.

**Comment by imartinflores** [comment]
@tpalus I am a little bit confused anyways, how is supposed to reach the EnterOneTimeCode , if the validation for a not null mfakey is made before that.

if (mfaSecretKey != null)
            {
                do
                {
                    entered = EnterOneTimeCode(driver, mfaSecretKey);


So it should only try to execute the "EnterOneTimeCode" if the mfa is not null
Unless it is empty, but the default value of mfakey is null on the login:

private LoginResult Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, SecureString mfaSecretKey = null, Action<LoginRedirectEventArgs> redirectAction = null)

**Comment by tpalus** [comment]
Can you record your login process? what happend after set up username,pass and click login

**Comment by imartinflores** [comment]
It just logins. Nothing else happens. But I am confused with the behaviour you mentioned anyways, cause it is not supposed to go through EnterOneTimeCode if the MFA is null, if it goes through, it means that mfa is not null, hence it should not be failing in the EnterOneTimeCode, I am trying to check why it can go through it.. unless I am missing something, or some other functionality where is calling that EnterOneTimeCode..

**Comment by tpalus** [comment]
yes but right after EnterOneTimeCode is function ClickStaySignedIn which will not be executed because my mfa is null. Maybe if you divide those function into 2 separate do loops.

**Comment by imartinflores** [comment]
It should not go through, the validation for mfa null is done before the do-while:

 if (mfaSecretKey != null)
            {
                do
                {
                    entered = EnterOneTimeCode(driver, mfaSecretKey);
                    success = ClickStaySignedIn(driver) || IsUserAlreadyLogged();
                    attempts++;
                }
                while (!success && attempts <= Constants.DefaultRetryAttempts); // retry to enter the otc-code, if its fail & it is requested again 
            }
            
            If you mfa is null, it should not be going through the do-while. If it is NULL, then it should go, and the methods inside should not throw any error, cause it has value,..

**Comment by tpalus** [comment]
Okay, I know what are you trying to achieve. But all I need is to click _Yes_ button on this dialog. And it is not possible if i set MFA null. 
image

**Comment by imartinflores** [comment]
Without mfa? Allright, think I got it now, so probably the one that needs to be updated is the EnterOneTimeCode

**Comment by tpalus** [comment]
@imartinflores Are you working on it?

**Comment by imartinflores** [comment]
@tpalus  I am not at the moment, feel free to revert if Tyler prefers. I dont have the option to run with Stay Log In, so it would be quite tricky for me as I can miss something else ... @TYLEROL

**Comment by tpalus** [comment]
@TYLEROL, Could you revert those changes please?

**Comment by imartinflores** [comment]
@tpalus  are you not up to work on it and make that change , so it still working for both ? As you have the example to run the login with Stay Login ?

**Comment by imartinflores** [comment]
In the image you sent above, the textbox to fill above "Stay Singed In", is the OTC Input or what is it?

**Comment by tpalus** [comment]
Nope, I don't think so. It is calling this function to looku for this dialog.
image

**Comment by imartinflores** [comment]
I think thats for the "Yes" button, but whats the textbox above ? is not to fill with the mfa ? I am trying to understand how the EnterOneTimeCode works, cause I cant replicate :\

**Comment by tpalus** [comment]
Can we connect somehow to solve this problem?

**Comment by bugboogie666** [comment]
Hi, a new version of Easy repro 9.2.21014.138 - trying to log in with this peace of code

        public static void LoginAndOpenDynamicsApp(string appName, Uri url, SecureString username, SecureString password)
        {            
            ObjectRepository.XrmApp.OnlineLogin.Login(url, username, password);          
            
            ObjectRepository.XrmApp.Navigation.OpenApp(appName);
        }

It has stopped to work after a new version was installed.
Easyrepro is not able to handle "Stay signed in?" dialog

Any workaround for this?

**Comment by imartinflores** [comment]
Happy to connect. I cant run it with Stay Signed In cause its not enabled on our product, but I assume a very quick workaround is just passing an empty ("") mfaKey on the login? Just by looking at the code.

**Comment by imartinflores** [comment]
Happy to connect, cant reproduce since I dont have the "Stay Signed In" option enabled, what if you pass an empty string as an mfa ? so it should go through the do-while again ?

**Comment by tpalus** [comment]
@imartinflores thanks! it works. I'm sending as MFA parameter "".toSecureString and it passes trough Stay signed dialog.

**Comment by imartinflores** [comment]
@tpalus happy to hear that! anyways, I think that should not be the case, its just a quick workaround, but happy to help again if you need to change the code for that. Sorry I missed it, is quite complicated cause I cant get to that screen, so not sure how it works.

**Comment by ewingjm** [comment]
@TYLEROL this has broke login for pretty much anyone not using MFA (I suspect a lot of people). Thankfully, there appears to be a workaround - but would it be possible to look at how we run can some automated tests on the PRs to avoid things like this in future?

**Comment by imartinflores** [comment]
@ewingjm This has broke login for the ones using Stay Signed In. For just MFA, it should not be affected. I Am not using MFA, and still working. The problem was that if you dont use MFA, BUT You need to click Stay Signed In, it will fail, cause without MFA it was not going through that method. But 100% agree with you, there should be a way of troubleshoot this before merging. Is not possible for me atm to debug this login to Stay Signed In, cause that option is not enabled on my product..so I have missed that part.

**Comment by ewingjm** [comment]
@imartinflores ah, so it's essentially the tenant having 'Show option to remain signed in' enabled in Azure AD as well as not passing any argument for the MFA parameter.  That is the default setting for tenants if branding is not configured so I suspect a common scenario for most dev/test tenants.

**Comment by imartinflores** [comment]
Yes, its been disabled long ago on the product and unfortunately I have no control on that. So my bad, I've missed that scenario for the Stay Signed In without using an MFA..

**Comment by AngelRodriguez8008** [comment]
@imartinflores I implement MFA in this way. By adding this condition, you are maybe saving a few seconds but your don't return the right error in case if there is a Dialog MFA but the key is not configured in app.config.

I tried many configurations, in a new Enviroment, i also disable the 'Show option to remain signed in' in AD and everythig still working fine.

Why was this change required?

Here are is my tests:

[Microsoft.Dynamics365.UIAutomation.Sample/UCI/Login/LoginWhitoutTestBase.cs](https://github.com/microsoft/EasyRepro/pull/1149/files#diff-6a0015ea640d1db9944159a7976df4db3d7e5123ed74033f58c587ffc7dcf8f2)

[Microsoft.Dynamics365.UIAutomation.Sample/UCI/Login/Login.cs](https://github.com/microsoft/EasyRepro/pull/1149/files#diff-5a20441d3a57ebe517b204e807bc58c27e5b75c85e361b8e71d3c0d3d19de564)

Please consider review the rollback.

**Pull request merged**
