### PR TITLE
Fix issues on GetHeaderTitle and OpenRecord

### PR DESCRIPTION
**Pull request by Ashfaq-ali**
### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (updates to documentation, formatting, etc.)

### Description
Wave 2 release related issues: 
Update to Grid container Xpath
Fetch headerTitle from title attribute instead of Text

### Issues addressed
https://github.com/microsoft/EasyRepro/issues/1179
https://github.com/microsoft/EasyRepro/issues/1172

### All submissions:

- [x] My code follows the code style of this project.
- [ ] Do existing samples that are effected by this change still run?
- [ ] I have added samples for new functionality. 
- [ ] I raise detailed error messages when possible.
- [ ] My code does not rely on labels that have the option to be hidden.

### Which browsers was this tested on?

- [x ] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge

### CODE REVIEW

**Review by AmarSinghMSFT — COMMENTED** [review]
I tried these changes for OpenRecord. It doesn't work for me.
I am using this version of CRM Online:
2021 release wave 1 enabled
Server version: 9.2.21081.00147
Client version: 1.4.3101-2108.1

**Comment by Ashfaq-ali** [comment]
> I tried these changes for OpenRecord. It doesn't work for me.
> I am using this version of CRM Online:
> 2021 release wave 1 enabled
> Server version: 9.2.21081.00147
> Client version: 1.4.3101-2108.1

Hi, 

Thanks for reviewing.
This fix is specifically for the Wave 2 release, I assume wave2 fixes will be packaged as a new version. 

I have tested against CRM version

2021 release wave 2 enabled
Server version: 9.2.21084.00137
Client version: 1.4.3129-2108.4

Thanks,
Ash

**Comment by TYLEROL** [comment]
@Ashfaq-ali - Can you please re-target this towards the new branch 'develop-2021ReleaseWave2'? This branch will be used for 2021 Release Wave 2 fixes (and eventually pushed back into Develop once the platform has a common base)

**Comment by Ashfaq-ali** [comment]
@TYLEROL Sure, switched to develop-2021ReleaseWave2 branch. Thanks

**Review by TYLEROL — APPROVED** [review]

**Pull request merged**
