### PR TITLE
Add Support for Access "More Command" on RelatedGrid CommandBar

### LINKED ISSUE #587: Not able to click on command bar.I have shown the diff where it is not working with images.
Image-1

**As shown in the above image code working fine.**

Image-2
**For this code is not working** 
_**xrmApp.CommandBar.ClickCommand("Add New Contact");**

### PR DESCRIPTION
**Pull request by dylanhaskins**
### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (updates to documentation, formatting, etc.)

### Description
Depending on screen Resolution (and other factors) Buttons on SubGrids in Unified Interface could be hidden under the "More Command" ellipses (...) in which case RelatedGrid.ClickCommand would not find the Button. Extended the ClickCommand method to support searching for the button on a named RelatedGrid using xrmApp.RelatedGrid.ClickCommand("New Order", null, true, "Orders") for public void ClickCommand(string name, string subName = null, bool moreCommands = false, string gridName = null);

### Issues addressed
Depending on screen Resolution (and other factors) Buttons on SubGrids in Unified Interface could be hidden under the "More Command" ellipses (...) in which case RelatedGrid.ClickCommand would not find the Button. Extended the ClickCommand method to support searching for the button on a named RelatedGrid using xrmApp.RelatedGrid.ClickCommand("New Order", null, true, "Orders") for public void ClickCommand(string name, string subName = null, bool moreCommands = false, string gridName = null);

Possibly fixes https://github.com/microsoft/EasyRepro/issues/587

### All submissions:

- [x] My code follows the code style of this project.
- [x] Do existing samples that are effected by this change still run?
- [ ] I have added samples for new functionality. 
- [x] I raise detailed error messages when possible.
- [x] My code does not rely on labels that have the option to be hidden.

### Which browsers was this tested on?

- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge

### CODE REVIEW

**Review by TYLEROL — APPROVED** [review]

**Comment by TYLEROL** [comment]
@dylanhaskins - As an FYI - I am merging a new change that is going to end up reverting some of your change here.

Within the next week, I'll be introducing a new Subgrid page which is intended to interact with Subgrids directly on an entity form. Related grid will function if you access a related entity via the 'Related' tab. 

I'll try to make the new subgrid interactions dynamic and not require a boolean input for 'More Commands'. I apologize for not catching this last week when I reviewed the PR and that you were focusing on subgrids.

Regards,
Tyler

**Comment by dylanhaskins** [comment]
Thanks @TYLEROL , no issue, it was nice to see a few posts over the last 2 weeks where that command was used at least, look forward to seeing the new Subgrid page :)

I was about to PR another Subgrid addition, allowing the clicking of the "Select All" toggle, do you want me to PR that anyway so that you can reference or include it as you see fit ? 

Looks like this (obviously there are AppElementReferences that go with the commit) : 


        public BrowserCommandResult<bool> ClickSubgridSelectAll(string sectionName, int thinkTime = Constants.DefaultThinkTime)
        {
            ThinkTime(thinkTime);

            return this.Execute(GetOptions("Click Select All Button on Grid"), driver =>
            {
                //Look for Section
                if (driver.HasElement(By.XPath(AppElements.Xpath[AppReference.Entity.SubGridSection].Replace("[NAME]", sectionName))))
                {
                    var section = driver.FindElement(By.XPath(AppElements.Xpath[AppReference.Entity.SubGridSection].Replace("[NAME]", sectionName)));

                    if (!section.HasElement(By.XPath(AppElements.Xpath[AppReference.Entity.SubGridSelectAll])))
                        throw new NotFoundException("Select All button not found");

                    section.FindElement(By.XPath(AppElements.Xpath[AppReference.Entity.SubGridSelectAll])).Click(true);

                    driver.WaitForTransaction();
                }

                return true;
            });
        }

Additionally I have a PR for a bug fix on the XPath for Related_CommandBarButton as the current XPath doesn't seem to work. New XPath is  

//Related Grid
            { "Related_CommandBarButton", "//button[@*[contains(., '[NAME]')] and @*[contains(.,'SubGrid')]]"},

Let me know if you want those and I will PR them in.

Regards,

Dylan.

**Comment by TYLEROL** [comment]
@dylanhaskins - If you don't mind - please post the PRs and I'll review them for inclusion into our other upcoming grid changes.

-Tyler

**Comment by 1301950** [comment]
Hi, has the merge happened yet? @TYLEROL

**Comment by 1301950** [comment]
the following line still returns null:

                var relatedCommandBarButtonList = driver.WaitUntilAvailable(By.XPath(AppElements.Xpath[AppReference.Related.CommandBarButtonList]));

because the data-lp-id it looks for is 

"//ul[contains(@data-lp-id, 'commandbar-SubGridAssociated')]"

and the nearest commandbar i can find has the id of:

"commandbar-SubGridStandard:[NAME]".

I do find something similar in the current appelements, but it's used by subgrid. But for associative grid, you are intending us to use relatedgrid, are you?

**Pull request merged**
