### PR TITLE
Update AppElementReference.cs - Fixed XPath for Entity Save button

### PR DESCRIPTION
**Pull request by AmarSinghMSFT**
Fixed XPath for Entity Save button

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (updates to documentation, formatting, etc.)

### Description
Fixed XPath for Entity Save button as the current XPath is not working.
Validated the fixed XPath in below 2 versions:
Version1 :
2021 release wave 1 enabled
Server version: 9.2.21084.00149
Client version: 1.4.3167-2108.4

Version2:
2021 release wave 2 enabled
Server version: 9.2.21093.00138
Client version: 1.4.3224-2109.3

### Issues addressed
https://github.com/microsoft/EasyRepro/issues/1208

### All submissions:

- [x] My code follows the code style of this project.
- [x] Do existing samples that are effected by this change still run?
- [ ] I have added samples for new functionality. 
- [ ] I raise detailed error messages when possible.
- [x] My code does not rely on labels that have the option to be hidden.

### Which browsers was this tested on?

- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge

### CODE REVIEW

**Review by amars4u — APPROVED** [review]
Validated the change and it has resolved the issue in my project.

**Comment by AmarSinghMSFT** [comment]
@aliyoussefi  / @TYLEROL  Requesting you to please check and approve this PR. Because of this issue Save is not working any team is blocked since last week. Also I would request to release new Version of NuGet as soon as possible as we are using NuGets.

**Review by prakashm625 — APPROVED** [review]

**Comment by ewingjm** [comment]
@AmarSinghMSFT I think this is to do with the footer removal in release wave 2, right? There should be a fix already in #1206.

**Comment by AmarSinghMSFT** [comment]
> @AmarSinghMSFT I think this is to do with the footer removal in release wave 2, right? There should be a fix already in #1206.

@ewingjm We are facing this issue in Wave1 and the XPath for Save button available on formula ribbon bar is not working.

Below is the version we are using for our SIT instance.
2021 release wave 1 enabled
Server version: 9.2.21084.00149
Client version: 1.4.3167-2108.4

**Review by TYLEROL — APPROVED** [review]

**Pull request merged**
