### PR TITLE
Replace all instances of 'mfaSecrectKey' with 'mfaSecretKey'

### PR DESCRIPTION
**Pull request by bwmodular**
### Type of change
- [] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (updates to documentation, formatting, etc.)

### Description
Replace all instances of 'mfaSecrectKey' with 'mfaSecretKey'

### Issues addressed

It might seem trivial, but anyone searching for the word 'secret' wont find it, so I think this typo is important to fix.

### All submissions:

- [X] My code follows the code style of this project.
- [X] Do existing samples that are effected by this change still run?
- [N/A] I have added samples for new functionality. 
- [N/A] I raise detailed error messages when possible.
- [N/A] My code does not rely on labels that have the option to be hidden.

### Which browsers was this tested on?

- [X] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge

### CODE REVIEW

**Review by TYLEROL — CHANGES_REQUESTED** [review]
Looks good - and thanks for the catch on this recent change! 

Will need a merge conflict fix prior to approval though due to a recent merge.

**Comment by bwmodular** [comment]
> 
> 
> Looks good - and thanks for the catch on this recent change!
> 
> Will need a merge conflict fix prior to approval though due to a recent merge.

Thanks @TYLEROL. Is that (merge conflict fix) something that you do or I need to do? Sorry, already at the full extent of my Git knowledge with this PR! :-)

**Review by TYLEROL — APPROVED** [review]

**Comment by TYLEROL** [comment]
@bwmodular - It looks like I was able to correct the conflicts via the site and commit them. I'll merge this PR now. 👍

**Comment by bwmodular** [comment]
@TYLEROL I'm not sure what has happened, but TestsBase class still has a reference to _mfaSecrectKey which means that the project won't compile.

I don't really understand how this could have happened as it wasn't like that in the version I commited (it wouldn't have compiled like that) so maybe something went wrong in the merge? 

Look at: 
https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/UCI/TestsBase.cs 

Line 20 declares the variable as _mfaSecretKey but line 64 references it as _mfaSecrectKey

Could you take a look and see if you can workout what's gone on?

**Comment by TYLEROL** [comment]
@bwmodular - I went and took a look on my current PR branch and it looks like that's the only reference that got missed, and by missed - it appears this may have been one of the conflict lines I amended. I was pretty confident I validated the change before I committed it back to your branch, but it seems this one either got missed or didn't change as expected.

I've added a small change to this existing PR I am working on - #793 . Should have that in later today.

-Tyler

**Pull request merged**
