### PR TITLE
fix for issue 1087 due to recent release of Dynamics 365 (commandbar …

### PR DESCRIPTION
**Pull request by 3dmundbarton**
### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (updates to documentation, formatting, etc.)

### Description
fix for issue 1087 due to recent release of Dynamics 365 (commandbarnow has extra <button> in DOM for each commandbar item.  Updated logic to locate commandbar items

### Issues addressed
#1087 

### All submissions:

- [ Y ] My code follows the code style of this project.
- [ n/a ] Do existing samples that are effected by this change still run? - this requirement involves procurement and configuration of a D365 environment - **would greatly appreciate if anyone else can run the EasyRepro samples and let me know if there are failures**
- [ n/a ] I have added samples for new functionality. 
- [ n/a ] I raise detailed error messages when possible.
- [ Y ] My code does not rely on labels that have the option to be hidden.

### Which browsers was this tested on?

- [ n/a ] Chrome
- [ n/a ] Firefox
- [ n/a ] IE
- [ n/a ] Edge

### CODE REVIEW

**Review by imartinflores — APPROVED** [review]

**Review by imartinflores — APPROVED** [review]

**Review by Haywaii — APPROVED** [review]

**Comment by Haywaii** [comment]
@TYLEROL can someone from the dev team approve it please? :)

**Review by tpalus — APPROVED** [review]
I tested on my Environment and it worked!

**Comment by imartinflores** [comment]
@tpalus could you please have a look at this one when you have some free time ? https://github.com/microsoft/EasyRepro/pull/1089

thanks in advance

**Comment by KumarSoniLove** [comment]
@thathi Please could you look into this asap. If there is a need to publish Nuget package with other changes, we would like to know how long it would take as at present, we have lot of test failures and continuous deployment means it would be difficult to track/confirm if there are real failures or any real functionality broken. Thanks in advance for looking into @dtu11 please could you assist. thanks

**Comment by tpalus** [comment]
> @tpalus could you please have a look at this one when you have some free time ? #1089
> 
> thanks in advance

I never set up or use mfa for easyrepro. But if i find some free time, i'll give it a shot :)

**Comment by imartinflores** [comment]
@tpalus  yeah, we are not using it, thats why I;ve added that condition to not even check if the element is there or not.
 Thanks!

**Comment by 3dmundbarton** [comment]
@TYLEROL @dtu11 - Hi gents, any chance you can look at this PR?  It's to fix a blocking defect #1087

**Review by TYLEROL — APPROVED** [review]

**Comment by imartinflores** [comment]
@TYLEROL Thanks, sorry to bother, is it already pushed to nuget or not yet ?

**Pull request merged**
