### PR TITLE
feat: 2021 release wave 2

### LINKED ISSUE #800: [BUG] XrmApp.Grid.GetGridItems() resultset: GUIDs and URLs are incorrect
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Calling the XrmApp.Grid's method `GetGridItems()` results in a List with wrong GUIDs and URLs for all the elements.
The GUID in the property Id is an empty GUID (`00000000-0000-0000-0000-000000000000`), while the id parameter in the Url property is not empty but the same for all items - see screenshot

**Code to reproduce**  
```csharp
xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);
xrmApp.Navigation.OpenApp(_myapp);
xrmApp.Navigation.OpenSubArea("My CRM", "contacts");
var contacts = xrmApp.Grid.GetGridItems();    // contacts[n].Id == `{00000000-0000-0000-0000-000000000000}`
```

 
**Expected behavior**  
The Id property contains the actual GUID of the record and the Url property contains this same GUID as the id-parameter.

**Screenshots**  
getgriditmes

**Additional context**  
For context:
In the screenshot, `nonlife_innovationproject` is a custom entity. `name` holds the subject of the recently created `Innovation Project`, while `innoGuid` holds its GUID. The `Assert` in line 97 fails, because the GUID in the resultset of `_xrmApp.Grid.GetGridItems()` is an empty GUID.
Mind that the displayed result set in the watch is not the one filtered by calling `Search(name)` (line 93), but only to demonstrate that the mentioned issue is true for all records.

### LINKED ISSUE #1139: [BUG] Xrm.<Entity|QuickCreate>.SetValue is not correctly setting Time component of DateTime field.
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
Xrm.<Entity|QuickCreate>.SetValue is not working when setting a DateTime field. The Date element is set correctly, but the time is not. Have tried both overrides available, passing a DateTimeControl or passing a DateTime, neither set the Time correctly.

**Special formatting / display**  
None.

**Code to reproduce**  

```csharp
xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);
xrmApp.Navigation.OpenApp(UCIAppName.Sales);
xrmApp.Navigation.QuickCreate("contact");
xrmApp.Entity.SetValue("my_dateandtimefield", DateTime.Now);
```
 
**Expected behavior**  
For the Time component of the DateTime field to be set.

### LINKED ISSUE #1140: [BUG] XrmApp.BusinessProcessFlow.SetValue fails to set the value of a Yes/No field
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
XrmApp.BusinessProcessFlow.SetValue fails to set the value of a Yes/No field. The XPath value for AppReference.BusinessProcessFlow.BooleanFieldSelectedOption assumes the Yes/No field is represented by a checkbox, which is not the case for custom business process flows in the latest Online version, they're represented by a dropdown.

**Code to reproduce**  
```csharp
XrmApp.BusinessProcessFlow.SetValue(new BooleanItem()
{
    Name = "my_yesnofield",
    Value = true,
});
```
 
**Expected behavior**  
For the Yes/No field to be set correctly.

**Screenshots**  
image

**Additional context**  
I can see this problem has been mentioned in the comments of this PR: https://github.com/microsoft/EasyRepro/pull/1036

### LINKED ISSUE #1169: Getting System.InvalidOperationException: 'Unable to Click the PickViewer', while using the function - SwitchView in the Grid.
Visual Studio Code:
xrmApp.Grid.SwitchView("zz_Admin-Child Accts SubGrid view");

Exception details:
System.InvalidOperationException: 'Unable to Click the View Picker'

This exception was originally thrown at this call stack:
    Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.SwitchView.AnonymousMethod__0(OpenQA.Selenium.IWebDriver) in WebClient.cs
    Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand<TReturn>.ExecuteCommand(OpenQA.Selenium.IWebDriver, object[]) in DelegateBrowserCommand.cs
    Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand<TReturn>.Execute<T1, T2, T3, T4, T5, T6, T7, T8, T9>(OpenQA.Selenium.IWebDriver, T1, T2, T3, T4, T5, T6, T7, T8, T9) in BrowserCommand.cs
    [External Code]
    Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.SwitchView(string, string, int) in WebClient.cs
    Microsoft.Dynamics365.UIAutomation.Api.UCI.Grid.SwitchView(string, string) in Grid.cs
    Microsoft.Dynamics365.UIAutomation.Sample.UCI.AA.CNT_CreateContactConnectedToAccount.UCITestCNT_CreateContactConnectedToAccount(System.Uri, System.Security.SecureString, System.Security.SecureString, string) in CNT_CreateContactConnectedToAccount.cs
    Microsoft.Dynamics365.UIAutomation.Sample.UCI.AA.CNT_CreateContactConnectedToAccount.UCICNT_CreateContactConnectedToAccount() in CNT_CreateContactConnectedToAccount.cs

### LINKED ISSUE #1171: Support for EasyRepro Dynamics 2021 release wave 2
## Question

Hi, Could you please advise if there are plans/timescale to support the 2021 Release Wave 2 version of Dynamics 365? We have updated one of our testing environments to the update scheduled for release in October via early access and noticed quite a substantial impact on our automation test scripts. Your answers will help us plan our remediation effort accordingly.

Thanks in Advance.

Nidhi

### LINKED ISSUE #1172: [BUG] Failed to open record from the grid using xrmApp.Grid.OpenRecord(0); - Early access - Dynamics 2021 release wave 2
**CRM Version:**
2021 release wave 2 enabled (Early access)

**UCI or Classic Web**
- [x] UCI (XrmApp)
- [ ] Classic Web (XrmBrowser)

**Browser**
- [x] Chrome

**Issue Description**
While testing the test environment which enabled with the early access version of Dynamics 2021 release wave 2 (release in October), EasyRepro failed to open the first record which present in the Grid table

**Method Used**
xrmApp.Grid.OpenRecord(0);

**Error Message**
input cannot be null
Parameter name: input

**StackTrace** 
   at OpenQA.Selenium.Support.UI.DefaultWait`1..ctor(T input, IClock clock)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntil(ISearchContext driver, Func`2 searchFunc, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, String exceptionMessage)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass72_0.<OpenRecord>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenRecord(Int32 index, Int32 thinkTime, Boolean checkRecord)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Grid.OpenRecord(Int32 index)

### LINKED ISSUE #1175: [BUG] Exception: ' Unable to Click the View Picker', while using the function - SwitchView in the Grid
Our Test environment recently updated to release wave 2.

After that, Switch view function on Grid throwing exception :  Unable to Click the View Picker

**Error:**

System.InvalidOperationException: Unable to click the View Picker
Stack Trace:
<>c__DisplayClass52_0.<WaitUntilClickable>b__0()
SeleniumExtensions.WaitUntil(ISearchContext driver, Func`2 searchFunc, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, String exceptionMessage)
SeleniumExtensions.ClickWhenAvailable(ISearchContext driver, By by, Nullable`1 timeout, String errorMessage)
<>c.<OpenViewPicker>b__72_0(IWebDriver driver)
DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
BrowserCommand`1.Execute(IWebDriver driver)
BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
WebClient.OpenViewPicker(Int32 thinkTime)
<>c__DisplayClass73_0.<SwitchView>b__0(IWebDriver driver)
DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
WebClient.SwitchView(String viewName, String subViewName, Int32 thinkTime)
Grid.SwitchView(String viewName, String subViewName)
TestHelixUpdateProject.HelixUpdateProject() line 66

### LINKED ISSUE #1176: [BUG] xrmApp.Grid.GetGridItems().Count throwing exception after release wave 2 update in Test environment
**Error:**

Test method Microsoft.Dynamics365.UIAutomation.SuccessHubTesting.vNext.Session.TestCreateSession.CreateSession threw exception:
OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".wj-colheaders"} (Session info: chrome=92.0.4515.131)

**Browser:**

Chrome

### LINKED ISSUE #1178: [BUG] Function xrmApp.Entity.SubGrid.OpenSubGridRecord("subgridname", 0); throwing exception after wave 2 release in Test environment
**Exception:**

Test method Microsoft.Dynamics365.UIAutomation.SuccessHubTesting.vNext.SessionRegistration.TestUpdateSessionRegistration.UpdateSessionToLive threw exception:
OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@data-id,'cell-0-1') and contains(@data-lp-id,'SessionRegistration')]"}
(Session info: chrome=92.0.4515.131)

### LINKED ISSUE #1179: [BUG] xrmApp.Grid.OpenRecord(0) throwing exception after wave 2 release in our Test environment
**Exception:**

System.ArgumentNullException: input cannot be null
Parameter name: input
Error Message
at OpenQA.Selenium.Support.UI.DefaultWait`1..ctor(T input, IClock clock)
at OpenQA.Selenium.Support.UI.DefaultWait`1..ctor(T input)
at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntil(ISearchContext driver, Func`2 searchFunc, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, String exceptionMessage)
at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Action`1 successCallback, String exceptionMessage)
at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass73_0.<OpenRecord>b__0(IWebDriver driver)
at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenRecord(Int32 index, Int32 thinkTime, Boolean checkRecord)
at Microsoft.Dynamics365.UIAutomation.Api.UCI.Grid.OpenRecord(Int32 index)

### LINKED ISSUE #1180: [BUG] xrmApp.Entity.SubGrid.GetSubGridItemsCount("subgridname") returning zero after recent wave 2 update in Test environment
**Exception:**

This method is not returning any errors but returning the count of records as 0 when there are records present in the subgrid.

### LINKED ISSUE #1181: [BUG] xrmApp.Grid.SwitchView("View name") throwing exception after recent wave 2 release in our Test environment
**Exception:**

System.InvalidOperationException: Unable to click the View Picker
Stack Trace:
<>c__DisplayClass52_0.<WaitUntilClickable>b__0()
SeleniumExtensions.WaitUntil(ISearchContext driver, Func`2 searchFunc, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
SeleniumExtensions.WaitUntilClickable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, String exceptionMessage)
SeleniumExtensions.ClickWhenAvailable(ISearchContext driver, By by, Nullable`1 timeout, String errorMessage)
<>c.<OpenViewPicker>b__72_0(IWebDriver driver)
DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
BrowserCommand`1.Execute(IWebDriver driver)
BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
WebClient.OpenViewPicker(Int32 thinkTime)
<>c__DisplayClass73_0.<SwitchView>b__0(IWebDriver driver)
DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
WebClient.SwitchView(String viewName, String subViewName, Int32 thinkTime)
Grid.SwitchView(String viewName, String subViewName)
TestHelixUpdateProject.HelixUpdateProject() line 66

### LINKED ISSUE #1195: Easy Repro Release Wave 2 Update - When will it happen?
## When will Easy Repro receive the update to work with D365 Release Wave 2?
Is there any prediction to when that will happen?

### PR DESCRIPTION
**Pull request by ewingjm**
### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (updates to documentation, formatting, etc.)

### Description
An assortment of fixes and enhancements around 2021 release wave 2.

### Issues addressed
Support for 2021 release wave 2.

Resolves #1139, resolves #1195, resolves #1181, resolves #1180, resolves #1179, resolves #1178, resolves #1176, resolves #1175, resolves #1172, resolves #1171, resolves #1169, resolves #1140, resolves #1139, resolves #800 

### All submissions:

- [x] My code follows the code style of this project.
- [x] Do existing samples that are effected by this change still run?
- [x] I have added samples for new functionality. 
- [x] I raise detailed error messages when possible.
- [x] My code does not rely on labels that have the option to be hidden.

### Which browsers was this tested on?

- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge

### CODE REVIEW

**Comment by ewingjm** [comment]
@TYLEROL creating this as draft until I'm satisfied all affected samples are green. I've tried to avoid breaking changes where possible e.g. `Lookup.SwitchView` will internally open the new Advanced Lookup dialog (it's no longer possible to switch the view on the lookup itself) and all the `Lookup` methods have been updated to work with either the Advanced Lookup dialog or the standard lookup results flyout. I haven't added methods to work with the new Advanced Lookup dialog directly as I just want this to be the bare minimum to support existing tests on wave 2.

**Comment by ewingjm** [comment]
Hi, @TYLEROL. I think I'm happy with where this is at now. Would it be possible to get a pre-release NuGet version out so people have the option to switch over before the end of the rollout this month?

**Comment by TYLEROL** [comment]
@ewingjm - Would you be able to update this and point it at the new develop-2021ReleaseWave2 branch? There has been 1 extra PR committed to the RW2 branch, so that may be the only conflict to potential resolve with a merge.

For at least a short period of time, we'll be operating two branches (RW1 = develop, RW2 = develop-2021ReleaseWave2). We're sorting out a tagging system for NuGet, but plan to release an RW2 version soon.

**Comment by ewingjm** [comment]
Thanks, @TYLEROL - sounds good. Merged and updated the target branch.

**Review by TYLEROL — APPROVED** [review]

**Pull request merged**
